### ISSUE TITLE
Junk Timestamps At End of TDMS Files

### ISSUE THREAD

**Issue by keenanjohnson** [LabVIEW-DCAF/TDMSModule#18]
Whenever the files close out (either with the shutdown state or the enable tag), the last few timestamps in the file are not accurate.

The data appears to be valid for those samples, but the timestamps have to be manually corrected.

**Comment by smithed** [comment]
unless its been changed, this is expected if annoying behavior. This module uses the tdms advanced api to make things as fast as possible, and that API requires a fixed number of writes per channel. So the module buffers data in chunks of that size and then writes to disk. If the module is stopped or paused before the buffer is full, it still must dump that data to disk. if i remember correctly it deliberately sets a junk value for time.

A workaround would be to, on the last dataset, simply close the file in adv mode and reopen in regular tdms mode. I didn't think of it before but this might work just fine. The last write will be slower but its not a huge deal.

**Comment by pollockm** [comment]
Implemented @smithed 's solution, along with the log rotate request.
