### ISSUE TITLE
File Name Requires .tdms but Doesn't Notify User

### ISSUE THREAD

**Issue by Beazurt** [LabVIEW-DCAF/TDMSModule#30]
Ideally we append the file extension ourselves (it is the .tdms module after all), but if we want the user to add the file extension then we should warn them in the UI.

Also, if the extension isn't added, the module ends up creating a file anyway at runtime using the module's GUID for the file name, instead of using the name the user entered. This is also confusing behavior that could be improved.

**Comment by jwgorman** [comment]
Acceptance Criteria:
- Automatically add .tdms to the end of the file name
- Show the full file path to the user
- Manual validation that the file is created as expected
- Unit test for verifying the .tdms is appended
