### ISSUE TITLE
Add x64 Targets as Supported

### ISSUE THREAD

**Issue by Beazurt** [LabVIEW-DCAF/TDMSModule#31]
You can't currently add the TDMS module to 64 Linux targets.

**Comment by pollockm** [comment]
...is an alternate solution to this simply to remove the distinction?  We don't have 32 vs 64 on any other target type, and we don't actually check the target to see if the remote system matches this value.  Maybe just a LinuxRT option?

**Comment by ryanpopo** [comment]
That's strange, because I just used TDMS on a 9036 the other day. Unless, something else has changed since then.

**Comment by Beazurt** [comment]
Are there cases where we would need to deploy different types of built code
to the target depending on whether it was 32 or 64-bit? If so it might be
better to leave the distinction. That is the only case I can think of that
could matter though.

**Comment by pollockm** [comment]
@ryanpopo  - the runtime code works fine on x64, but the editor node is not available if you manually switch the type of the cRIO target from Linux RT ARM (default) to Linux RT 64

**Comment by pollockm** [comment]
@beazurt - there are, usually in cases where we call into an SO file.  For example, syslog.  In that case I actually push over BOTH the arm and x64 versions of the SO to the target and do a runtime check of which one to cal.  @ryanpopo  - how did you handle this for the shared memory?

**Comment by ryanpopo** [comment]
So on the editor side, we didn't care about the target type. Runtime would just handle it.

**Comment by Beazurt** [comment]
Makes sense to deploy both and decide at runtime based on the target type. Honestly the less a user needs to care about the OS and architecture the better. It should be OK to try changing the enum and make sure nothing goes terribly wrong.

**Comment by smithed** [comment]
If you're deploying you could technically check the 64/32 distinction when you connect to the target and decide on the appropriate binaries to deploy then. I think we only added the distinction so that the callback to get any files to deploy could check that its sending the right one.

Probably easier to just send all of them, though, like you are :)

**Comment by jwgorman** [comment]
Acceptance Criteria
- x64 should be added to the list
- Create another issue to resolve the larger issue of whether we need the distinction (this is relevant for new TSN module)
