### ISSUE TITLE
Move Module Documentation from NI Forums to README

### ISSUE THREAD

**Issue by jacobson3** [LabVIEW-DCAF/TDMSModule#53]
Documentation currently exists on the NI forums. This should be moved into the README and updated for content correctness and clarity.

**Comment by SimonRPSM** [comment]
Hey there, @jacobson3 - I am marking this one as complete because I believe you have done the vast majority of these.

**Comment by jacobson3** [comment]
@SimonRPSM , the base documentation has been moved over but is not in the main branch yet. I was in the process of updating the documentation but got pulled into other things.

**Comment by SimonRPSM** [comment]
Got it!

**Comment by jacobson3** [comment]
Fixed in #56
